// <auto-generated />
using System;
using BlazorCrudProject.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorCrudProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorCrudProject.DataAccess.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Age = 39,
                            DateOfBirth = new DateTime(1985, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "John Moxley",
                            PhoneNumber = 98632540
                        },
                        new
                        {
                            EmployeeId = 2,
                            Age = 34,
                            DateOfBirth = new DateTime(1990, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Sarah Smith",
                            PhoneNumber = 98632540
                        },
                        new
                        {
                            EmployeeId = 3,
                            Age = 36,
                            DateOfBirth = new DateTime(1988, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Michael Johnson",
                            PhoneNumber = 98632540
                        },
                        new
                        {
                            EmployeeId = 4,
                            Age = 29,
                            DateOfBirth = new DateTime(1995, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            FullName = "Emily Davis",
                            PhoneNumber = 98632540
                        },
                        new
                        {
                            EmployeeId = 5,
                            Age = 32,
                            DateOfBirth = new DateTime(1992, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            FullName = "David Wilson",
                            PhoneNumber = 98632540
                        },
                        new
                        {
                            EmployeeId = 6,
                            Age = 37,
                            DateOfBirth = new DateTime(1987, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            FullName = "Linda Martinez",
                            PhoneNumber = 98632540
                        },
                        new
                        {
                            EmployeeId = 7,
                            Age = 31,
                            DateOfBirth = new DateTime(1993, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Logistics",
                            FullName = "James Brown",
                            PhoneNumber = 98632540
                        },
                        new
                        {
                            EmployeeId = 8,
                            Age = 33,
                            DateOfBirth = new DateTime(1991, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Support",
                            FullName = "Olivia Taylor",
                            PhoneNumber = 98632540
                        },
                        new
                        {
                            EmployeeId = 9,
                            Age = 38,
                            DateOfBirth = new DateTime(1986, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "R&D",
                            FullName = "William Harris",
                            PhoneNumber = 98632540
                        },
                        new
                        {
                            EmployeeId = 10,
                            Age = 30,
                            DateOfBirth = new DateTime(1994, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            FullName = "Sophia Anderson",
                            PhoneNumber = 98632540
                        },
                        new
                        {
                            EmployeeId = 11,
                            Age = 35,
                            DateOfBirth = new DateTime(1989, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            FullName = "Benjamin Clark",
                            PhoneNumber = 98632540
                        },
                        new
                        {
                            EmployeeId = 12,
                            Age = 27,
                            DateOfBirth = new DateTime(1997, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            FullName = "Mia Lewis",
                            PhoneNumber = 98632540
                        },
                        new
                        {
                            EmployeeId = 13,
                            Age = 40,
                            DateOfBirth = new DateTime(1984, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            FullName = "Alexander Lee",
                            PhoneNumber = 98632540
                        },
                        new
                        {
                            EmployeeId = 14,
                            Age = 28,
                            DateOfBirth = new DateTime(1996, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            FullName = "Isabella Walker",
                            PhoneNumber = 98632540
                        },
                        new
                        {
                            EmployeeId = 15,
                            Age = 41,
                            DateOfBirth = new DateTime(1983, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            FullName = "Henry Hall",
                            PhoneNumber = 98632545
                        },
                        new
                        {
                            EmployeeId = 16,
                            Age = 26,
                            DateOfBirth = new DateTime(1998, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Support",
                            FullName = "Charlotte Young",
                            PhoneNumber = 98632540
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
